package com.example.demo.domain;

import java.util.Date;

public class ProductDetailInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail_info.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail_info.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail_info.PARAM_ID
     *
     * @mbggenerated
     */
    private Long paramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail_info.PARAM_NAME
     *
     * @mbggenerated
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail_info.PARAM_VALUE
     *
     * @mbggenerated
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_detail_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail_info.ID
     *
     * @return the value of product_detail_info.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail_info.ID
     *
     * @param id the value for product_detail_info.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail_info.PRODUCT_ID
     *
     * @return the value of product_detail_info.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail_info.PRODUCT_ID
     *
     * @param productId the value for product_detail_info.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail_info.PARAM_ID
     *
     * @return the value of product_detail_info.PARAM_ID
     *
     * @mbggenerated
     */
    public Long getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail_info.PARAM_ID
     *
     * @param paramId the value for product_detail_info.PARAM_ID
     *
     * @mbggenerated
     */
    public void setParamId(Long paramId) {
        this.paramId = paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail_info.PARAM_NAME
     *
     * @return the value of product_detail_info.PARAM_NAME
     *
     * @mbggenerated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail_info.PARAM_NAME
     *
     * @param paramName the value for product_detail_info.PARAM_NAME
     *
     * @mbggenerated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail_info.PARAM_VALUE
     *
     * @return the value of product_detail_info.PARAM_VALUE
     *
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail_info.PARAM_VALUE
     *
     * @param paramValue the value for product_detail_info.PARAM_VALUE
     *
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail_info.CREATE_TIME
     *
     * @return the value of product_detail_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail_info.CREATE_TIME
     *
     * @param createTime the value for product_detail_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_detail_info.UPDATE_TIME
     *
     * @return the value of product_detail_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_detail_info.UPDATE_TIME
     *
     * @param updateTime the value for product_detail_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}