package com.example.demo.domain;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.PRODUCT_TYPE
     *
     * @mbggenerated
     */
    private Integer productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.PRODUCT_TITLE
     *
     * @mbggenerated
     */
    private String productTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.PRODUCT_PIC
     *
     * @mbggenerated
     */
    private String productPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.PRODUCT_FEATURE_ID
     *
     * @mbggenerated
     */
    private String productFeatureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.PRODUCT_PARAM
     *
     * @mbggenerated
     */
    private String productParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_main.PRODUCT_INTRO
     *
     * @mbggenerated
     */
    private String productIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.PRODUCT_ID
     *
     * @return the value of product_main.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.PRODUCT_ID
     *
     * @param productId the value for product_main.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.PRODUCT_TYPE
     *
     * @return the value of product_main.PRODUCT_TYPE
     *
     * @mbggenerated
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.PRODUCT_TYPE
     *
     * @param productType the value for product_main.PRODUCT_TYPE
     *
     * @mbggenerated
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.PRODUCT_NAME
     *
     * @return the value of product_main.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.PRODUCT_NAME
     *
     * @param productName the value for product_main.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.PRODUCT_TITLE
     *
     * @return the value of product_main.PRODUCT_TITLE
     *
     * @mbggenerated
     */
    public String getProductTitle() {
        return productTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.PRODUCT_TITLE
     *
     * @param productTitle the value for product_main.PRODUCT_TITLE
     *
     * @mbggenerated
     */
    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle == null ? null : productTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.PRODUCT_PIC
     *
     * @return the value of product_main.PRODUCT_PIC
     *
     * @mbggenerated
     */
    public String getProductPic() {
        return productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.PRODUCT_PIC
     *
     * @param productPic the value for product_main.PRODUCT_PIC
     *
     * @mbggenerated
     */
    public void setProductPic(String productPic) {
        this.productPic = productPic == null ? null : productPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.CREATE_TIME
     *
     * @return the value of product_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.CREATE_TIME
     *
     * @param createTime the value for product_main.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.UPDATE_TIME
     *
     * @return the value of product_main.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.UPDATE_TIME
     *
     * @param updateTime the value for product_main.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.PRODUCT_FEATURE_ID
     *
     * @return the value of product_main.PRODUCT_FEATURE_ID
     *
     * @mbggenerated
     */
    public String getProductFeatureId() {
        return productFeatureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.PRODUCT_FEATURE_ID
     *
     * @param productFeatureId the value for product_main.PRODUCT_FEATURE_ID
     *
     * @mbggenerated
     */
    public void setProductFeatureId(String productFeatureId) {
        this.productFeatureId = productFeatureId == null ? null : productFeatureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.PRODUCT_PARAM
     *
     * @return the value of product_main.PRODUCT_PARAM
     *
     * @mbggenerated
     */
    public String getProductParam() {
        return productParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.PRODUCT_PARAM
     *
     * @param productParam the value for product_main.PRODUCT_PARAM
     *
     * @mbggenerated
     */
    public void setProductParam(String productParam) {
        this.productParam = productParam == null ? null : productParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_main.PRODUCT_INTRO
     *
     * @return the value of product_main.PRODUCT_INTRO
     *
     * @mbggenerated
     */
    public String getProductIntro() {
        return productIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_main.PRODUCT_INTRO
     *
     * @param productIntro the value for product_main.PRODUCT_INTRO
     *
     * @mbggenerated
     */
    public void setProductIntro(String productIntro) {
        this.productIntro = productIntro == null ? null : productIntro.trim();
    }
}