package com.example.demo.domain;

import java.util.Date;

public class ProductAppEnv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_app_env.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_app_env.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_app_env.APP_ENV
     *
     * @mbggenerated
     */
    private String appEnv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_app_env.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_app_env.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_app_env.ID
     *
     * @return the value of product_app_env.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_app_env.ID
     *
     * @param id the value for product_app_env.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_app_env.PRODUCT_ID
     *
     * @return the value of product_app_env.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_app_env.PRODUCT_ID
     *
     * @param productId the value for product_app_env.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_app_env.APP_ENV
     *
     * @return the value of product_app_env.APP_ENV
     *
     * @mbggenerated
     */
    public String getAppEnv() {
        return appEnv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_app_env.APP_ENV
     *
     * @param appEnv the value for product_app_env.APP_ENV
     *
     * @mbggenerated
     */
    public void setAppEnv(String appEnv) {
        this.appEnv = appEnv == null ? null : appEnv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_app_env.CREATE_TIME
     *
     * @return the value of product_app_env.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_app_env.CREATE_TIME
     *
     * @param createTime the value for product_app_env.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_app_env.UPDATE_TIME
     *
     * @return the value of product_app_env.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_app_env.UPDATE_TIME
     *
     * @param updateTime the value for product_app_env.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}