package com.example.demo.domain;

public class Rank2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank2.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank2.songListId
     *
     * @mbggenerated
     */
    private Long songlistid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank2.consumerId
     *
     * @mbggenerated
     */
    private Long consumerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank2.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank2.id
     *
     * @return the value of rank2.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank2.id
     *
     * @param id the value for rank2.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank2.songListId
     *
     * @return the value of rank2.songListId
     *
     * @mbggenerated
     */
    public Long getSonglistid() {
        return songlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank2.songListId
     *
     * @param songlistid the value for rank2.songListId
     *
     * @mbggenerated
     */
    public void setSonglistid(Long songlistid) {
        this.songlistid = songlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank2.consumerId
     *
     * @return the value of rank2.consumerId
     *
     * @mbggenerated
     */
    public Long getConsumerid() {
        return consumerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank2.consumerId
     *
     * @param consumerid the value for rank2.consumerId
     *
     * @mbggenerated
     */
    public void setConsumerid(Long consumerid) {
        this.consumerid = consumerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank2.score
     *
     * @return the value of rank2.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank2.score
     *
     * @param score the value for rank2.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}