package com.example.demo.domain;

import java.util.Date;

public class TrafficStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_statistics.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_statistics.ENTITY_ID
     *
     * @mbggenerated
     */
    private Long entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_statistics.ENTITY_NAME
     *
     * @mbggenerated
     */
    private String entityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_statistics.BROWSE_TIME
     *
     * @mbggenerated
     */
    private Date browseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column traffic_statistics.BROWSE_IP
     *
     * @mbggenerated
     */
    private String browseIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_statistics.ID
     *
     * @return the value of traffic_statistics.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_statistics.ID
     *
     * @param id the value for traffic_statistics.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_statistics.ENTITY_ID
     *
     * @return the value of traffic_statistics.ENTITY_ID
     *
     * @mbggenerated
     */
    public Long getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_statistics.ENTITY_ID
     *
     * @param entityId the value for traffic_statistics.ENTITY_ID
     *
     * @mbggenerated
     */
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_statistics.ENTITY_NAME
     *
     * @return the value of traffic_statistics.ENTITY_NAME
     *
     * @mbggenerated
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_statistics.ENTITY_NAME
     *
     * @param entityName the value for traffic_statistics.ENTITY_NAME
     *
     * @mbggenerated
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName == null ? null : entityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_statistics.BROWSE_TIME
     *
     * @return the value of traffic_statistics.BROWSE_TIME
     *
     * @mbggenerated
     */
    public Date getBrowseTime() {
        return browseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_statistics.BROWSE_TIME
     *
     * @param browseTime the value for traffic_statistics.BROWSE_TIME
     *
     * @mbggenerated
     */
    public void setBrowseTime(Date browseTime) {
        this.browseTime = browseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column traffic_statistics.BROWSE_IP
     *
     * @return the value of traffic_statistics.BROWSE_IP
     *
     * @mbggenerated
     */
    public String getBrowseIp() {
        return browseIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column traffic_statistics.BROWSE_IP
     *
     * @param browseIp the value for traffic_statistics.BROWSE_IP
     *
     * @mbggenerated
     */
    public void setBrowseIp(String browseIp) {
        this.browseIp = browseIp == null ? null : browseIp.trim();
    }
}