package com.example.demo.dao;

import com.example.demo.domain.ProductDetailInfo;

public interface ProductDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail_info
     *
     * @mbggenerated
     */
    int insert(ProductDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail_info
     *
     * @mbggenerated
     */
    int insertSelective(ProductDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail_info
     *
     * @mbggenerated
     */
    ProductDetailInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_detail_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDetailInfo record);
}