package com.example.demo.dao;

import java.util.List;

import com.example.demo.domain.Product;

public interface ProductMapper {

    int addProduct(Product product);

    int deleteByProuductId(Long productId);

    int updateProduct(Product product);
    
    int updateProductPic(Product product);
    
    int updateProductParam(Product product);
    
    Product productOfId(Long productId);
    
    List<Product> allProducts();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_main
     *
     * @mbggenerated
     */
    int insertSelective(Product product);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_main
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Product product);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Product product);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_main
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);
    
    
    




	List<Product> productOfName(String productName);

	List<Product> productOfType(Long productType);

	
}