package com.example.demo.dao;

import com.example.demo.domain.ProductAppEnv;

public interface ProductAppEnvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_app_env
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_app_env
     *
     * @mbggenerated
     */
    int insert(ProductAppEnv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_app_env
     *
     * @mbggenerated
     */
    int insertSelective(ProductAppEnv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_app_env
     *
     * @mbggenerated
     */
    ProductAppEnv selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_app_env
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductAppEnv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_app_env
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductAppEnv record);
}