package com.example.demo.dao;

import com.example.demo.domain.Rank2;

public interface Rank2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank2
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank2
     *
     * @mbggenerated
     */
    int insert(Rank2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank2
     *
     * @mbggenerated
     */
    int insertSelective(Rank2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank2
     *
     * @mbggenerated
     */
    Rank2 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Rank2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank2
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Rank2 record);
}