package com.example.demo.dao;

import java.util.List;

import com.example.demo.domain.SongList;

public interface SongListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int insert(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int insertSelective(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    SongList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SongList record);
    
    
    int updateSongListMsg(SongList record);

    int updateSongListImg(SongList record);

    int deleteSongList(Integer id);

    List<SongList> allSongList();

    List<SongList> likeTitle(String title);

    List<SongList> likeStyle(String style);

    List<SongList> songListOfTitle(String title);
}